config/routes.rb
Rails.application.routes.draw do
  
 
  devise_for :users, controllers: {   registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :books
  root to: 'books#top'
  root 'books#index'
  get 'home/about' => 'users#about'
  resources :users, only: [:show, :edit, :update, :index]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

         has_many :books, dependent: :destroy
         def posts
          return Post.where(user_id: self.id)
        end
        attachment :profile_image
        
        validates :introduction,length: {maximum: 50 }
        validates :name,presence: true,length: {in: 2..20 }
        
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  def after_sign_up_path_for(resource)
    user_path(resource)
  end 
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource)
    user_path(resource)
  end 


  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit,:index,:show]
  
  
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    end

    def edit
      @user = User.find(params[:id])
      if current_user != @user
        redirect_to user_path(current_user.id)
  
      end
  end
    def index
      @users = User.all
      @user = current_user
      @book = Book.new
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "Info was successfully created."
    redirect_to user_path(@user.id)
    else
    render 'edit'
    end
end
private 
def user_params
    params.require(:user).permit(:name, :introduction,:profile_image)
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/about.html.erb
<div class="about">
<h1>Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers!</h1>
</div>

app/views/users/edit.html.erb
<div class="user-edit">

<h1>User info</h1>
<%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
      <p>1 error prohibited this obj from being saved: <br>
      Introduction is too long (maximum is 50 characters)</p>
   <% end %>
<div>
<table>
      <tr>
      <td>Name</td>
      <td><%= f.text_field :name, autofocus: true, placeholder:"Name"%></td>
      </tr>
      <tr>
      <td>Introduction</td>
      <td><%= f.text_area :introduction %></td>
      </tr>
      <tr>
      <td>ProfileImage</td>
      <td><%= f.attachment_field :profile_image, placeholder: "Image", class: "user-edit-form" %></td>
      </tr>
</table>

 </div>            

<%= f.submit "Update User", class: "btn btn-default"%>
<% end %>
</div>

app/views/users/index.html.erb
<div class="container"> 
<div class="row">
 <div class="col-xs-3">
  <div class="profile-container">
   <h1>User info</h1>
   <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
   <table class="table table-striped">
   <tr>
   <td>
   <h3>name:</h3>
   </td>
   <td>
   <h3 class="profile-name"><%= @user.name %></h3>
   </td>
   <td>
   </tr>
   
   <tr>
   <td>
   <h3>introduction:</h3>
   </td>
   <td>
   <h3 class="profile-introduction"><%= @user.introduction %></h3>
   </td>
   </tr>
   </table>
    <% if @user.id == current_user.id %>
        <p><%= link_to "Edit", edit_user_path(@user), class: "btn btn-default"%></p>
    <% end %>
  
  </div>



  <h2>New book</h2>
    <%= form_for(@book) do |f| %>
       <% if @book.errors.any? %>
       <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
       <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <h4>Title</h4>
      <%= f.text_field :title %>
      
      <h4>Opinion</h4>
      <%= f.text_area :body %>
      
      <%= f.submit 'Create Book' %>
      
      <% end %>
      
      </div>   


<div class="col-xs-9">
    <h1 class="users-heading">Users</h1>
    <table class="table table-striped">
   <thead>
      <tr>
         <th>image</th>
         <th>name</th>
         <th colspan="3"></th>
      </tr>
   </thead>
   <tbody>
    <% @users.each do |user| %>
      <tr>
      <td><%= attachment_image_tag user, :profile_image,  format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", size: "35x35" %> </td>
      <td><%= user.name %><td/>
      <td class = "show"><%=link_to 'Show', user_path(user.id) %></td>
      </tr>
    <% end %>
    </tbody>
    </table>
 </div>
 </div>
 </div>
    

app/views/users/show.html.erb
<% if flash[:notice] %>
   <div class="flash">
     <%= flash[:notice] %>
   </div>
 <% end %>


<div class="container"> 
<div class="row">
 <div class="col-xs-3">

<div class="profile-container">
   <h1>User info</h1>
   <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
   <table class="table table-striped">
   <tr>
   <td>
   <h3>name:</h3>
   </td>
   <td>
   <h3 class="profile-name"><%= @user.name %></h3>
   </td>
   <td>
   </tr>
   <tr>
   <td>
   <h3>introduction:</h3>
   </td>
   <td>
   <h3 class="profile-introduction"><%= @user.introduction %></h3>
   </td>
   </tr>
   </table>
    <% if @user.id == current_user.id %>
        <p><%= link_to "Edit", edit_user_path(@user), class: "btn btn-default" %></p>
    <% end %>
    </table>
</div>


<h2>New book</h2>
<%= form_for(@book) do |f| %>
   <% if @book.errors.any? %>
   <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
   <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
 
    <h4>Title</h4>
    <%= f.text_field :title %>
  
    <h4>Opinion</h4>
    <%= f.text_area :body %>
 
    <%= f.submit 'Create Book' %>

    <% end %>
</div>
<div class="col-xs-9">
<h1>Books</h1>
<table class="table table-striped">
   <thead>
      <tr>
         <th>Title</th>
         <th>Opinion</th>
         <th colspan="3"></th>
      </tr>
   </thead>
 <tbody>
   <% @books.each do |book| %>
      <tr>
      <td><%= attachment_image_tag @user, :profile_image,  format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", size: "35x35"  %></td>
         <td><%=link_to book.title,book_path(book.id) %></td>
         <td><%=book.body %></td>
      </tr>
         <% end %>
 </tboby>
</table>
</div>
</div>