config/routes.rb
Rails.application.routes.draw do
  
 
  devise_for :users, controllers: {   registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :books
  root to: 'books#top'
  root 'books#index'
  get 'home/about' => 'users#about'
  resources :users, only: [:show, :edit, :update, :index]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user, optional: true
  validates :title, presence: true
  validates :body, presence: true,length: {maximum: 200 }
  def user
    return User.find_by(id: self.user_id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:edit,:index,:show]
  def top
  end
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
       flash[:notice] = "Book was successfully created."
       redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render action: :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @newbook = Book.new
    @users = User.all
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if current_user != @book.user
      redirect_to books_path

    end

  end

  def update
      @book = Book.find(params[:id])
      if @book.update(book_params)
        flash[:notice] = "Book was successfully updated."
         redirect_to book_path(@book.id)
      else
        render action: :edit
      end
  end

  def destroy
  	book = Book.find(params[:id])
        book.destroy
        redirect_to books_path
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>


<div class="user-edit">

<h1>Editing Book</h1>
<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>
  <% if @book.errors.any? %>
  <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
    <h4>title</h4>
    <%= f.text_field :title %>
    <h4>body</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Update Book', class: "btn btn-default" %>    
<% end %>

<%= link_to "Show", book_path(@book.id) %>
<%= link_to "Back", books_path %>

</div>

app/views/books/index.html.erb
<div class="container"> 
<div class="row">
 <div class="col-xs-3">
<div class="profile-container">
<h1>User info</h1>
<%=  attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
<table class="table table-striped">
   <tr>
   <td>
   <h3>name:</h3>
   </td>
   <td>
   <h3 class="profile-name"><%= @user.name %></h3>
   </td>
   <td>
   </tr>
   <tr>
   <td>
   <h3>introduction:</h3>
   </td>
   <td>
   <h3 class="profile-introduction"><%= @user.introduction %></h3>
   </td>
   </tr>
   </table>
 <% if @user.id == current_user.id %>
     <p><%= link_to "Edit", edit_user_path(@user), class: "btn btn-default" %></p>
 <% end %>
</div>

<h2>New book</h2>
<%= form_for(@book) do |f| %>
   <% if @book.errors.any? %>
   <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
   <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  
  <%= f.submit 'Create Book' %>
  
  <% end %>
  
  </div>

<div class="col-xs-9">
<h1>Books</h1>
<table class="table table-striped">
   <thead>
      <tr>
         <th>Title</th>
         <th>Opinion</th>
         <th colspan="3"></th>
      </tr>
   </thead>
 <tbody>
   <% @books.each do |book| %>
      <tr>
         <td><%=link_to user_path(book.user.id) do%>
            <%= attachment_image_tag book.user, :profile_image,  format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", size: "35x35" %> 
            <%end%>
            </td>
         <td><%=link_to book.title,book_path(book.id) %></td>
         <td><%=book.body %></td>
      </tr>
 </tboby>
   <% end %>
</table>
</div>
</div>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
<p><%= flash[:notice] %></p>
<% end %>

<div class="container"> 
<div class="row">
 <div class="col-xs-3">
<h1>User info</h1>
   <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
   <table class="table table-striped">
   <tr>
   <td>
   <h3>name:</h3>
   </td>
   <td>
   <h3 class="profile-name"><%= @user.name %></h3>
   </td>
   <td>
   </tr>
   <tr>
   <td>
   <h3>introduction:</h3>
   </td>
   <td>
   <h3 class="profile-introduction"><%= @user.introduction %></h3>
   </td>
   </tr>
   </table>
    <% if @user.id == current_user.id %>
        <p><%= link_to "Edit", edit_user_path(@user), class: "btn btn-default" %></p>
    <% end %>

<h2>New book</h2>
    <%= form_for(@newbook) do |f| %>
       <% if @book.errors.any? %>
       <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
       <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
     
        <h4>Title</h4>
        <%= f.text_field :title %>
      
        <h4>Opinion</h4>
        <%= f.text_area :body %>
     
        <%= f.submit 'Create Book' %>
    
        <% end %>
</div>

<div class="col-xs-9">
<h1>Book detail</h1>
<table class="table table-striped">
<tr>
<td><%=link_to user_path(@book.user.id) do%>
<%= attachment_image_tag @book.user, :profile_image,  format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", size: "35x35" %> 
<%end%>
</td>
<td><%=link_to user_path(@book.user.id) do%>
<%= @user.name %>
<%end%>
</td>
<td><%=@book.title %></td>
<td><%=@book.body %></td>
<% if @user.id == current_user.id %>
<td><%= link_to "Edit", edit_book_path(@book.id) %></td>
<td><%=link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
<% end %>
</tr>
</table>
</div>
</div>
</div>

app/views/books/top.html.erb
<% if flash[:notice] %>
   <div class="flash">
     <%= flash[:notice] %>
   </div>
 <% end %>

<div class="main">
<h1>welcome to<strong><span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers</strong>  !!</h1>
</div>

<div class="sentence">
<p>In<strong><span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers</strong>, </p>
<p>you can share and exchange  your opinions , inpressions , and emotions</p>
<p> about various books!</p>
<%= link_to "Log in", user_session_path, class: "btn btn-info"%>
<% if user_signed_in? %>
<%= link_to "Sign Up", user_path(current_user), class: "btn btn-success" %>

<%else%>
<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success" %>

<%end%>

</div>