config/routes.rb
Rails.application.routes.draw do
  
 
  devise_for :users, controllers: {   registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :books
  root to: 'books#top'
  root 'books#index'
  get 'home/about' => 'users#about'
  resources :users, only: [:show, :edit, :update, :index]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
   
   <nav class="navbar navbar-default">
	  <div class="container-fluid">
		<div class="navbar-header">
      <div class="bookers">
      <span>Bookers</span>
      </div>
      <div class="collapse navbar-collapse" id="navbarEexample1">
			<ul class="nav navbar-nav">
   <% if user_signed_in? %>
   <li>
   <%= link_to " Home", user_path(current_user.id),class: "glyphicon glyphicon-home" %>
   </li>

   <li>
   <%= link_to " Users", users_path, class:"glyphicon glyphicon-user" %>
   </li>

   <li>
   <%= link_to " Books", books_path,class:"glyphicon glyphicon-book" %>
   </li>

   <li>
   <%= link_to " logout", destroy_user_session_path, method: :delete, class:"glyphicon glyphicon-inbox" %>
   </li>
   <% else %>
   <li> 
   <%= link_to " Home", root_path,class:"glyphicon glyphicon-home" %>
   </li>

   <li>
   <%= link_to " About", home_about_path ,class:"glyphicon glyphicon-search"  %>
   </li>

   <li>
   <%= link_to " sign up", new_user_registration_path,class:"glyphicon glyphicon-edit" %>
   </li>

   <li>
   <%= link_to " Login", user_session_path,class:"glyphicon glyphicon-share"  %>
   </li>

   <% end %>
   </ul>
   </div>
 </div>
</nav>
   </header>
   
   
   <% if flash[:alert] %>
   <div class="flash">
     <%= flash[:alert] %>
   </div>
 <% end %>
   
    <%= yield %>
  </body>
</html>